/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetStaticProps } from "next";
import Link from "next/link";
import { Button } from "@mui/material";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js!</h1>
        <Button variant="contained" size="large" href={"/isr"}>
          isr動作確認ページへ
        </Button>
      </main>
    </div>
  );
}
